/**Auto-generated by: https://github.com/angular-threejs/gltf
Command: npx angular-three-gltf&#64;1.0.16 public/Ghost_Skull.gltf -o src/app/experience/ghost-skull-model.ts --selector app-ghost-skull-model --name GhostSkullModel --transform
**/

import type * as THREE from 'three'
import { Group, SkinnedMesh } from 'three'
import {
  extend,
  NgtGroup,
  NgtObjectEvents,
  NgtObjectEventsInputs,
  NgtObjectEventsOutputs,
  NgtArgs,
} from 'angular-three'
import {
  Component,
  ChangeDetectionStrategy,
  CUSTOM_ELEMENTS_SCHEMA,
  Signal,
  input,
  viewChild,
  ElementRef,
  inject,
  effect,
  computed,
  model,
} from '@angular/core'
import { injectGLTF } from 'angular-three-soba/loaders'
import { GLTF } from 'three-stdlib'
import { injectAnimations, NgtsAnimationClips, NgtsAnimationApi } from 'angular-three-soba/misc'

type ActionName = 'Death' | 'Fast_Flying' | 'Flying_Idle' | 'Headbutt' | 'HitReact' | 'No' | 'Punch' | 'Yes'
type GhostSkullModelAnimationClips = NgtsAnimationClips<ActionName>
export type GhostSkullModelAnimationApi = NgtsAnimationApi<GhostSkullModelAnimationClips> | null
export type GhostSkullModelGLTFResult = GLTF & {
  animations: GhostSkullModelAnimationClips[]
  nodes: {
    Ghost_Skull: THREE.SkinnedMesh
    Root: THREE.Bone
  }
  materials: {
    Atlas: THREE.MeshStandardMaterial
  }
}

@Component({
  selector: 'app-ghost-skull-model',
  standalone: true,
  template: `
    @if (gltf(); as gltf) {
      <ngt-group #model [parameters]="options()">
        <ngt-group name="Scene">
          <ngt-group name="CharacterArmature">
            <ngt-primitive *args="[gltf.nodes.Root]" />
            <ngt-skinned-mesh
              name="Ghost_Skull"
              [geometry]="gltf.nodes.Ghost_Skull.geometry"
              [material]="gltf.materials.Atlas"
              [skeleton]="gltf.nodes.Ghost_Skull.skeleton" />
          </ngt-group>
        </ngt-group>

        <ng-content />
      </ngt-group>
    }
  `,
  imports: [NgtArgs],
  hostDirectives: [
    {
      directive: NgtObjectEvents,
      inputs: NgtObjectEventsInputs,
      outputs: NgtObjectEventsOutputs,
    },
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class GhostSkullModel {
  protected readonly Math = Math

  options = input({} as Partial<NgtGroup>)
  animations = model<GhostSkullModelAnimationApi>()
  modelRef = viewChild<ElementRef<Group>>('model')

  protected gltf = injectGLTF(() => '/Ghost_Skull-transformed.glb', {
    useDraco: true,
  }) as unknown as Signal<GhostSkullModelGLTFResult | null>

  private scene = computed(() => {
    const gltf = this.gltf()
    if (!gltf) return null
    return gltf.scene
  })

  private objectEvents = inject(NgtObjectEvents, { host: true })

  constructor() {
    extend({ Group, SkinnedMesh })

    const animations = injectAnimations(this.gltf, this.scene)
    effect(
      () => {
        if (animations.ready()) {
          this.animations.set(animations)
        }
      },
      { allowSignalWrites: true },
    )

    effect(
      () => {
        const modelRef = this.modelRef()?.nativeElement
        if (!modelRef) return

        this.objectEvents.ngtObjectEvents.set(modelRef)
      },
      { allowSignalWrites: true },
    )
  }
}
